function renderSportTable() {
    return
    <table>
        <thead>
            <tr>
                <td>#</td>
                <td>Name</td>
                <td>Next game date</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>Krepsinis</td>
                <td>2024-07-06</td>
            </tr>
            <tr>
                <td>2</td>
                <td>Futbolas</td>
                <td>2024-07-05</td>
            </tr>
            <tr>
                <td>3</td>
                <td>Kvadratas</td>
                <td>2024-07-04</td>
            </tr>
        </tbody>
    </table>
}